### ISSUE TITLE
Spurious error messages with large dataset

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#127]
When processing the large dataset from Issue #126 , several spurious error messages like this appeared in the log:

```
tornado.application - ERROR - Uncaught exception PUT /api/jobs/80a452db-7d47-4a0e-8a29-677e5e907d54/ (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='PUT', uri='/api/jobs/80a452db-7d47-4a0e-8a29-677e5e907d54/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/uellue/libertem-venv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/uellue/libertem-venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/uellue/LiberTEM/LiberTEM/src/libertem/web/server.py", line 334, in put
    await job_runner.asend(results)
  File "/home/uellue/LiberTEM/LiberTEM/src/libertem/web/server.py", line 228, in run_job
    for result in results
  File "/home/uellue/LiberTEM/LiberTEM/src/libertem/web/server.py", line 122, in finish_job
    "details": self.data.serialize_job(job_id),
  File "/home/uellue/LiberTEM/LiberTEM/src/libertem/web/server.py", line 627, in serialize_job
    job = self.jobs[job_id]
KeyError: '80a452db-7d47-4a0e-8a29-677e5e907d54'
```

This doesn't happen with smaller data sets, at least I didn't observe it. Is it related to the problems that I experienced with processing this data set?

**Comment by sk1p** [comment]
This is a symptom of #126, closing.
