### ISSUE TITLE
Black frames in pick mode on Win 10

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#137]
When using pick mode on the Glasgow data set on a Windows 10 laptop, the GUI showed black frames for the detector every now and then.

The same happened for calculation results as well.

**Comment by uellue** [comment]
The bug can be reproduced with the most recent version. That is the error message:

```
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36': ()}
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000001ED2DFA40D0>, <Future finished exception=KeyError('<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36',)>)
Traceback (most recent call last):
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\ioloop.py", line 779, in _discard_future_result
    future.result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\client.py", line 3542, in track_future
    result = yield future._result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\client.py", line 216, in _result
    result = yield self.client._gather([self])
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\client.py", line 1483, in _gather
    self.futures[key].reset()
KeyError: '<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36'
[2018-10-24 15:41:04,108] INFO [libertem.web.server.log_message:32] message: START_JOB (job=7a946a25-ff58-4e5f-98f1-6c5e677cf0e8)
distributed.core - ERROR - '<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36'
Traceback (most recent call last):
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\core.py", line 374, in handle_stream
    handler(**merge(extra, msg))
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\scheduler.py", line 2777, in report_on_key
    ts = self.tasks[key]
KeyError: '<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36'
[2018-10-24 15:41:04,126] ERROR [asyncio.default_exception_handler:1268] Task was destroyed but it is pending!
task: <Task pending coro=<JobDetailHandler.put() done, defined at c:\users\weber\documents\libertem\libertem\src\libertem\web\server.py:317> wait_for=<Future pending cb=[_make_coroutine_wrapper.<locals>.wrapper.<locals>.<lambda>() at C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py:347, <TaskWakeupMethWrapper object at 0x000001ED2DCD9B58>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\ioloop.py:719]>
distributed.core - ERROR - '<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36'
Traceback (most recent call last):
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\core.py", line 320, in handle_comm
    result = yield result
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\scheduler.py", line 1924, in add_client
    yield self.handle_stream(comm=comm, extra={'client': client})
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\core.py", line 374, in handle_stream
    handler(**merge(extra, msg))
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\distributed\scheduler.py", line 2777, in report_on_key
    ts = self.tasks[key]
KeyError: '<libertem.job.raw.PickFrameTask object at 0x000001ED2DFD14A8>-37749e92180fbf7f576ece6cac2a5b36'
[2018-10-24 15:41:04,151] INFO [libertem.web.server.log_message:32] message: FINISH_JOB (job=7a946a25-ff58-4e5f-98f1-6c5e677cf0e8)
```

**Comment by sk1p** [comment]
Uhh, certainly... interesting :grin: can you check if you have the latest dask distributed version installed?

**Comment by sk1p** [comment]
I can reproduce the exception, which is related to job cancellation, but I don't get blank frames here. I do sometimes get partial frames (I'm testing with with K2 data), but that is expected if the pick job takes more than 300ms (for example if you scrub very fast with the pick handle). Do you get this with different datasets? Are you using a tileshape with whole frames, or one that splits the frames?

**Comment by uellue** [comment]
I'm testing on the BLO dataset. I'd have to download a K2 dataset to test on it.

```
(libertem) C:\Users\weber>pip show dask
Name: dask
Version: 0.18.2
Summary: Parallel PyData with Task Scheduling
Home-page: http://github.com/dask/dask/
Author: None
Author-email: None
License: BSD
Location: c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages
Requires:
Required-by: distributed

(libertem) C:\Users\weber>pip show distributed
Name: distributed
Version: 1.22.1
Summary: Distributed computing
Home-page: https://distributed.readthedocs.io/en/latest/
Author: Matthew Rocklin
Author-email: mrocklin@gmail.com
License: BSD
Location: c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages
Requires: click, psutil, sortedcontainers, six, dask, cloudpickle, pyyaml, tornado, zict, msgpack, toolz, tblib
Required-by: libertem
```


Parameter | Value
-- | --
path | C:\Users\weber\ownCloud\Projects\Open Pixelated STEM framework\Data\3rd-Party Datasets\Glasgow\10 um 110.blo
type | BLO
name | Glasgow: Ian MacLaren, Shane McCartan
tileshape | (1,8,144,144)
shape | (90,121,144,144)


Name | Value
-- | --
Partition shape | (22, 121, 144, 144)
Number of partitions | 5

**Comment by uellue** [comment]
I'm upgrading distributed to 1.23.3 and will retest.

**Comment by uellue** [comment]
I couldn't reproduce the behavior with the upgraded versions, `dask-0.19.4` and `distributed-1.23.3` . Exceptions show up frequently in the log, but they don't lead to blank frames. 

Should we require the newest versions for libertem or should we let nature run its course?

**Comment by sk1p** [comment]
LiberTEM already depends on distributed >= 1.23.2, and I am going to switch this over to >= 1.23.3 for the release.

My guess is that cancellation in a certain state triggers this exception, and that state rarely happens with smaller frames on my PC. It is possible that the cancellation-related exceptions we are seeing are just red herrings and are not directly related to the blank frames problem. From the construction of the frame picking in the client, there should definitely not be blank frames, and in case of cancellation, the last valid frame we received should be displayed instead, which is then replaced with the newly picked frame when the first result for the picking job returns.

Whatever the real reason may be, I'm going to update the distributed version and close this issue. If this re-appears, we can re-open this issue and debug further. Also easier if you are in the office :grin:. Thanks for testing!
