### ISSUE TITLE
Exception when doing COM analysis on ROI that touches the frame center

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#138]
I was trying a COM analysis on a very small ROI on the Glasgow data set, see screenshot. This made LiberTEM hang. On the command line with the output log I got an unhandled exception, see below. Upon trying different ROIs I noticed that this bug seems to be triggered when the ROI exactly touches the frame center. Note that the frame center in the Glasgow data set is slightly below the zero order peak.

![image](https://user-images.githubusercontent.com/25689052/47136136-0a626680-d2b3-11e8-8e40-2af4585f6046.png)

```
[2018-10-17 15:22:43,190] DEBUG [libertem.viz.ColormapCubehelix.rgb_from_vector:48] Calling rgb_from_vector
[2018-10-17 15:22:43,199] DEBUG [libertem.viz.interpolate_color:330] Calling interpolate_color
[2018-10-17 15:22:43,217] INFO [libertem.web.server.log_message:32] message: TASK_RESULT (job=0056a795-f4a4-4866-ae2e-b9a6c6801289)
[2018-10-17 15:22:43,716] DEBUG [libertem.viz.ColormapCubehelix.rgb_from_vector:48] Calling rgb_from_vector
[2018-10-17 15:22:43,722] DEBUG [libertem.viz.interpolate_color:330] Calling interpolate_color
[2018-10-17 15:22:43,768] INFO [libertem.web.server.log_message:32] message: TASK_RESULT (job=0056a795-f4a4-4866-ae2e-b9a6c6801289)
[2018-10-17 15:22:43,801] DEBUG [libertem.viz.ColormapCubehelix.rgb_from_vector:48] Calling rgb_from_vector
[2018-10-17 15:22:43,807] DEBUG [libertem.viz.interpolate_color:330] Calling interpolate_color
tornado.application - ERROR - Uncaught exception PUT /api/jobs/0056a795-f4a4-4866-ae2e-b9a6c6801289/ (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='PUT', uri='/api/jobs/0056a795-f4a4-4866-ae2e-b9a6c6801289/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\server.py", line 330, in put
    job_results=full_result,
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\server.py", line 53, in run_blocking
    return await tornado.ioloop.IOLoop.current().run_in_executor(None, partial(fn, *args, **kwargs))
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\analysis\com.py", line 34, in get_results
    AnalysisResult(raw_data=x_centers, visualized=visualize_simple(x_centers),
  File "c:\users\weber\documents\libertem\libertem\src\libertem\viz.py", line 390, in visualize_simple
    normalized = norm(result)
  File "C:\Users\weber\AppData\Local\conda\conda\envs\LiberTEM\lib\site-packages\matplotlib\colors.py", line 947, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue
```

**Comment by uellue** [comment]
Thx! Confirmed fixed. :-)
