### ISSUE TITLE
Point release 0.11.2?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1456]
Because of https://github.com/scikit-learn-contrib/hdbscan/issues/597, the following currently reproduces a crash:

$ conda create -n new-env python=3.11
$ conda activate new-env
$ pip install 'libertem[hdbscan]'
$ python -c 'import libertem.analysis.fullmatch'

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/libertem/analysis/fullmatch.py", line 4, in <module>
    import hdbscan
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/hdbscan/hdbscan_.py", line 40, in <module>
    FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"]
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'builtin_function_or_method'
```

I propose we do a stable release with mostly the changes from https://github.com/LiberTEM/LiberTEM/pull/1454

* 9d1b62f7 - Pin dask to !=2023.6.1
* f9f869c4 - Pin scikit-learn to <1.3.0
* 1352955a - Fix compatibility with latest scipy 

That should ensure the `hdbscan`-using code in LiberTEM works out of the box again.

(In the long run, it might be worthwhile to clean up this code, and move the matching to `libertem_blobfinder`, too, but that's for another day probably. Then we can remove the `hdbscan` extra dependency from LiberTEM itself completely, and only have to re-release `libertem_blobfinder` in case of issues like this)

**Comment by sk1p** [comment]
v0.11.2rc1 is confirmed to fix this issue, using the following commands: 

```bash
$ conda create -n new-env python=3.11
$ conda activate new-env
$ python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem[hdbscan]==0.11.2rc1'
$ python -c 'import libertem.analysis.fullmatch'
```

**Comment by sk1p** [comment]
v0.11.2 is now available on https://pypi.org/project/libertem/

I think we can skip this for CVL, as this is exclusively to fix dependency and testing issues.
