### ISSUE TITLE
Improve web GUI error reporting with invalid raw_csr

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#1464]
## How to reproduce

Open a raw_csr dataset with an indptr file size that is invalid for the dtype specified in the sparse.toml file in the web GUI.

## What happens

The web GUI closes the file browsing/opening view without an error message. On the console libertem-server shows the following:

```
2023-07-12 11:11:50,602 - distributed.worker - WARNING - Compute Failed
Key:       get_nav_size-af4fd8dd-67d5-4c39-b136-7ca9f070faec
Function:  get_nav_size
args:      ()
kwargs:    {}
Exception: "ValueError('Size of available data is not a multiple of the data-type size.')"

2023-07-12 11:11:50,603 - tornado.application - ERROR - Uncaught exception GET /api/datasets/detect/?path=%2Fdata%2Ftest%2FMeasurement_jul_12_2023_10h26m07s%2Fimage%2Fsparse0.toml (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/api/datasets/detect/?path=%2Fdata%2Ftest%2FMeasurement_jul_12_2023_10h26m07s%2Fimage%2Fsparse0.toml', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/web/dataset.py", line 147, in get
    detected_params = await sync_to_async(
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/common/async_utils.py", line 58, in sync_to_async
    return await loop.run_in_executor(pool, fn)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/common/async_utils.py", line 27, in _wrapped
    return f(*args, **kwargs)
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/io/dataset/__init__.py", line 232, in detect
    params = cls.detect_params(path, executor)
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/io/dataset/raw_csr.py", line 252, in detect_params
    image_count = executor.run_function(get_nav_size, descriptor=descriptor)
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/executor/dask.py", line 522, in run_function
    return future.result()
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/distributed/client.py", line 327, in result
    raise exc.with_traceback(tb)
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/libertem/io/dataset/raw_csr.py", line 438, in get_nav_size
    indptr = np.memmap(
  File "/home/asi/envs/libertem-venv/lib/python3.10/site-packages/numpy/core/memmap.py", line 239, in __new__
    raise ValueError("Size of available data is not a "
ValueError: Size of available data is not a multiple of the data-type size.
```

## What should happen

The error message is shown as an error in the web GUI and the user can continue browsing.

**Comment by sk1p** [comment]
> The error message is shown as an error in the web GUI and the user can continue browsing

Rough plan:

This means that `detect_params` needs to be able to throw a specific exception type, which signals "this is the correct data set type for this file, but I can't handle it for some other reason". If we just `return False`, we will get the open dialog with RAW selected as type, which can be confusing for users.

Dataset implementations then need to be updated to catch specific errors - this may be something we do over time to improve the user experience, whenever we catch these issues. For `raw_csr` this means after successfully loading the toml file, any exceptions need to be converted to the new exception type.

Then, this exception type needs to be propagated as [a custom message through the web API](https://github.com/LiberTEM/LiberTEM/blob/58e6a5803bce6f9fa7ff2a5bac85f19d114626b3/src/libertem/web/messages.py#L75-L82), similar to the current `DATASET_DETECTION_FAILED` message.

_Then_, this message needs to be handled in the client, basically [adding a variant to the `DetectDatasetResponse`](https://github.com/LiberTEM/LiberTEM/blob/58e6a5803bce6f9fa7ff2a5bac85f19d114626b3/client/src/messages.ts#L373-L385), which then [needs to be converted to an appropriate error message in the `doDetectDataset` saga](https://github.com/LiberTEM/LiberTEM/blob/58e6a5803bce6f9fa7ff2a5bac85f19d114626b3/client/src/dataset/sagas.ts#L46-L69).
