### ISSUE TITLE
Notebook export tests: thread unsafety inside `ipykernel`?

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1601]
I didn't yet dig deeper, but running `tests/server/test_copy.py::test_copy_notebook` with `PYTHONASYNCIODEBUG=1`, the following error is logged:

```
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 362, in process_control
    await result
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 986, in shutdown_request
    content = self.do_shutdown(parent["content"]["restart"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 638, in do_shutdown
    self.shell.exit_now = True
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __set__
    self.set(obj, value)
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 706, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 1513, in _notify_trait
    self.notify_change(
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 1525, in notify_change
    return self._notify_observers(change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 1568, in _notify_observers
    c(event)
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 476, in _update_exit_now
    loop.call_later(0.1, loop.stop)
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/tornado/ioloop.py", line 609, in call_later
    return self.call_at(self.time() + delay, callback, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/LiberTEM/.tox/web_api/.venv/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 216, in call_at
    return self.asyncio_loop.call_later(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda/envs/py311-data/lib/python3.11/asyncio/base_events.py", line 727, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda/envs/py311-data/lib/python3.11/asyncio/base_events.py", line 742, in call_at
    self._check_thread()
  File "/home/alex/miniconda/envs/py311-data/lib/python3.11/asyncio/base_events.py", line 800, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

Need to investigate what this is caused by.

**Comment by uellue** [comment]
Works on my machine™

Since it didn't seem to have cropped up after this or caused any problems for more than a year, I'll close. We can reopen if it happens again.
