### ISSUE TITLE
Exception when making ROI very small

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#368]
First of all, the ROI feature is AWESOME! I just found a tiny bug.

How to reproduce: Make the ROI very small (zero) in the GUI

What happens:
An exception is triggered:
```
[2019-06-18 08:13:56,750] ERROR [libertem.web.jobs.put:48] error running job, params={'dataset': '10970433-0628-4b41-8e86-6aee565bbf3f', 'analysis': {'type': 'SUM_FRAMES', 'parameters': {'roi': {'shape': 'disk', 'cx': 31.847456669143252, 'cy': 44.76476945244957, 'r': 0.2324687800192109}}}}
Traceback (most recent call last):
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\jobs.py", line 46, in put
    return await self.run_udf(uuid, ds, analysis)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\jobs.py", line 142, in run_udf
    udf_results=udf_results,
UnboundLocalError: local variable 'udf_results' referenced before assignment
tornado.application - ERROR - Uncaught exception PUT /api/jobs/9e4bf20b-e10a-4a37-9faf-c901085b870e/ (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='PUT', uri='/api/jobs/9e4bf20b-e10a-4a37-9faf-c901085b870e/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\weber\AppData\Local\conda\conda\envs\libertem\lib\site-packages\tornado\web.py", line 1543, in _execute
    result = yield result
  File "C:\Users\weber\AppData\Local\conda\conda\envs\libertem\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\jobs.py", line 53, in put
    job = analysis.get_job()
  File "c:\users\weber\documents\libertem\libertem\src\libertem\analysis\base.py", line 94, in get_job
    raise NotImplementedError()
NotImplementedError
```

What I expect to happen:
Empty result displayed on the left.

**Comment by sk1p** [comment]
Fixed in 361b7aea1b60717213806ac2f1048f31ce37fafb
