### ISSUE TITLE
Opening a HDF5 file that is not in 4D shape gives a confusing error message in the GUI

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#442]
How to reproduce: Open a HDF5 file with 3D contents with the GUI.

Observed behavior:

![image](https://user-images.githubusercontent.com/25689052/65579908-f9b57880-df78-11e9-9321-c8b119d901bd.png)

The server output is more helpful:
```
tornado.application - ERROR - Uncaught exception PUT /api/datasets/24793536-6195-477d-8080-b04381d5c04b/ (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='PUT', uri='/api/datasets/24793536-6195-477d-8080-b04381d5c04b/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\dataset.py", line 36, in put
    dataset_params = converter.to_python(params)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\messages.py", line 176, in to_python
    self.validate(raw_data)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\web\messages.py", line 170, in validate
    jsonschema.validate(schema=self.SCHEMA, instance=raw_data)
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\jsonschema\validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\jsonschema\validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: [1, 8, 157] is too short

Failed validating 'minItems' in schema['properties']['tileshape']:
    {'items': {'type': 'number'},
     'maxItems': 4,
     'minItems': 4,
     'type': 'array'}

On instance['tileshape']:
    [1, 8, 157]
```

Expected behavior:

An error message that gives more information on the cause of the error, for example the text of the exception.

See also #441!

**Comment by sk1p** [comment]
Related to #316 - this has actually multiple parts.

In case of an invalid message, the server should send some human-(and/or machine)-readable message instead of 500-crashing.

The GUI should then display this error in the correct context - in case of input-parameter related errors, the error should be displayed next to the input element.

In addition, the message can be pre-validated on the client-side, as we now have json schema definitions at least for opening datasets. Error-displaying as above also applies to this pre-validation, with some care taken regarding usability (in other words: it should not be annoying!).
