### ISSUE TITLE
Debug hangs of `Client.close` at the end of test runs

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#485]
At the end of test runs, we now had quite a few hanging CI jobs, and I could also locally reproduce this just using plain old `pytest tests/`. I dug into this and found out it hangs at the `atexit` function that closes the global client. One thing that came to light is that `Client.close()` of `distributed` doesn't pass on the `timeout` in the synchronous case - if I patch this in, I get the following traceback:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/clausen/.virtualenvs/libertem-debug/lib/python3.7/site-packages/distributed/client.py", line 4556, in _close_global_client
    c.close(timeout=2)
  File "/home/clausen/.virtualenvs/libertem-debug/lib/python3.7/site-packages/distributed/client.py", line 1346, in close
    sync(self.loop, self._close, fast=True, callback_timeout=timeout)
  File "/home/clausen/.virtualenvs/libertem-debug/lib/python3.7/site-packages/distributed/utils.py", line 328, in sync
    raise gen.TimeoutError("timed out after %s s." % (callback_timeout,))
tornado.util.TimeoutError: timed out after 2 s.
```

But now there are a few questions to answer:

 * Why is there a global client at all, where is it created? Did we miss a cleanup somewhere?
   * Idea: breakpoint: when the global `Client` is registered (or just raise an Exception there)
 * Is the timeout-ignoring of `.close()` a feature or a bug?
 * Why is the close function hanging at all? What is it waiting for?
 * Debugging with gdb showed quite a lot of threads, are we leaking somewhere?

**Comment by sk1p** [comment]
client.coroutines contains the following:

```
[<Task finished coro=<Client._handle_report() done, defined at /home/clausen/.virtualenvs/libertem-debug/lib/python3.7/site-packages/distributed/client.py:1151> exception=RuntimeError('generator raised StopIteration')>]
```

**Comment by sk1p** [comment]
Maybe these issues are also caused by our mocking of `time.time`? If there is some timeout functionality that relies on monotony of time, which is running in the background while we do our testing,  we may be breaking that...

**Comment by sk1p** [comment]
A dump of threads running when the hang occurs:

```
[<_MainThread(MainThread, stopped 140206564341568)>, <Thread(PyFFTWCacheThread, started daemon 140206306023168)>,
<Thread(IO loop, started daemon 140206356363008)>, <Thread(Profile, started daemon 140206314415872)>,
<Thread(TCP-Executor-20745-0, started daemon 140206398310144)>, <Thread(Dask-Offload_0, started daemon 140205890615040)>,
<Thread(TCP-Executor-20745-1, started daemon 140205340206848)>, <Thread(IO loop, started daemon 140205331814144)>,
<Thread(Profile, started daemon 140204811745024)>, <Thread(IO loop, started daemon 140204669118208)>,
<Thread(Profile, started daemon 140204803352320)>, <Thread(IO loop, started daemon 140204685903616)>,
<Thread(Profile, started daemon 140204702689024)>, <Thread(IO loop, started daemon 140204677510912)>,
<Thread(Profile, started daemon 140204576864000)>, <Thread(IO loop, started daemon 140204660725504)>,
<Thread(Profile, started daemon 140204560078592)>, <Thread(IO loop, started daemon 140204694296320)>,
<Thread(Profile, started daemon 140204543293184)>, <Thread(IO loop, started daemon 140204794959616)>,
<Thread(Profile, started daemon 140204711081728)>, <DummyProcess(Thread-1, started daemon 140204023207680)>,
<DummyProcess(Thread-2, started daemon 140204006422272)>, <DummyProcess(Thread-3, started daemon 140204534900480)>,
<DummyProcess(Thread-4, started daemon 140204014814976)>, <DummyProcess(Thread-5, started daemon 140204568471296)>,
<DummyProcess(Thread-6, started daemon 140204039993088)>, <DummyProcess(Thread-7, started daemon 140204031600384)>,
<DummyProcess(Thread-8, started daemon 140203998029568)>, <Thread(Thread-9, started daemon 140203989636864)>,
<Thread(Thread-10, started daemon 140203503122176)>, <Thread(Thread-11, started daemon 140203494729472)>,
<Thread(IO loop, started daemon 140204551685888)>, <Thread(Profile, started daemon 140203486336768)>,
<Thread(IO loop, started daemon 140202966251264)>, <Thread(Profile, started daemon 140203469551360)>,
<Thread(IO loop, started daemon 140202949465856)>, <Thread(Profile, started daemon 140203452765952)>,
<Thread(IO loop, started daemon 140204526507776)>, <Thread(Profile, started daemon 140202429380352)>,
<Thread(IO loop, started daemon 140202932680448)>, <Thread(Profile, started daemon 140202420987648)>,
<Thread(IO loop, started daemon 140202412594944)>, <Thread(Profile, started daemon 140202924287744)>,
<Thread(IO loop, started daemon 140202404202240)>, <Thread(Profile, started daemon 140202395809536)>,
<Thread(IO loop, started daemon 140202379024128)>, <Thread(Profile, started daemon 140201892509440)>,
<Thread(IO loop, started daemon 140202941073152)>, <Thread(Profile, started daemon 140201884116736)>,
<Thread(IO loop, started daemon 140201875724032)>, <Thread(Profile, started daemon 140201867331328)>,
<Thread(IO loop, started daemon 140201330460416)>, <Thread(Profile, started daemon 140201842153216)>,
<Thread(IO loop, started daemon 140201313675008)>, <Thread(Profile, started daemon 140201347245824)>,
<Thread(IO loop, started daemon 140202915895040)>, <Thread(Profile, started daemon 140203477944064)>,
<Thread(IO loop, started daemon 140201087203072)>, <Thread(Profile, started daemon 140201305282304)>,
<Thread(IO loop, started daemon 140201858938624)>, <Thread(Profile, started daemon 140201322067712)>,
<Thread(IO loop, started daemon 140201355638528)>, <Thread(Profile, started daemon 140202957858560)>]
```

**Comment by sk1p** [comment]
As the hangs did not re-appear since merging that commit, I'm going to close this issue
