### ISSUE TITLE
Python API: Consistency check of mask dimension and detector dimension

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#85]
Right now, when mask dimension and actual data don't match, the Simple API gives a long list of error messages like

```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000001D8C728B378>, <Future finished exception=ValueError('shapes (8,20736) and (16384,2) not aligned: 20736 (dim 1) != 16384 (dim 0)',)>)
Traceback (most recent call last):
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 779, in _discard_future_result
    future.result()
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\distributed\client.py", line 3542, in track_future
    result = yield future._result()
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\distributed\client.py", line 206, in _result
    six.reraise(*exc)
  File "c:\users\weber\appdata\local\conda\conda\envs\libertem\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\job\masks.py", line 129, in call
    result = data.dot(masks)
ValueError: shapes (8,20736) and (16384,2) not aligned: 20736 (dim 1) != 16384 (dim 0
```

For me this is hard to interpret.

Furthermore, the cell in a Jupyter notebook doesn't terminate and I have to stop and restart the kernel, and execute everything from the top.

Since this is a common mix-up, the Simple API should display a single more helpful message, something like "The provided mask has shape (128, 128), while the detector frame has shape (144, 144). Aborting."

Furthermore, it should terminate cleanly after that error message.

**Comment by uellue** [comment]
Current output in case of a size mismatch:

```
distributed.worker - WARNING -  Compute Failed
Function:  <libertem.job.masks.ApplyMasksTask object at 0x00000212D72A1C88>
args:      ()
kwargs:    {}
Exception: RuntimeError('size mismatch, m1: [8 x 16384], m2: [16256 x 1] at c:\\a\\w\\1\\s\\windows\\pytorch\\aten\\src\\th\\generic/THTensorMath.cpp:940',)

distributed.worker - WARNING -  Compute Failed
Function:  <libertem.job.masks.ApplyMasksTask object at 0x0000016635435668>
args:      ()
kwargs:    {}
Exception: RuntimeError('size mismatch, m1: [8 x 16384], m2: [16256 x 1] at c:\\a\\w\\1\\s\\windows\\pytorch\\aten\\src\\th\\generic/THTensorMath.cpp:940',)

distributed.worker - WARNING -  Compute Failed
Function:  <libertem.job.masks.ApplyMasksTask object at 0x00000166353A9E10>
args:      ()
kwargs:    {}
Exception: RuntimeError('size mismatch, m1: [8 x 16384], m2: [16256 x 1] at c:\\a\\w\\1\\s\\windows\\pytorch\\aten\\src\\th\\generic/THTensorMath.cpp:940',)

distributed.worker - WARNING -  Compute Failed
Function:  <libertem.job.masks.ApplyMasksTask object at 0x00000212D72A1E80>
args:      ()
kwargs:    {}
Exception: RuntimeError('size mismatch, m1: [8 x 16384], m2: [16256 x 1] at c:\\a\\w\\1\\s\\windows\\pytorch\\aten\\src\\th\\generic/THTensorMath.cpp:940',)

tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tornado\gen.py", line 970, in error_callback
    future.result()
concurrent.futures._base.CancelledError
Traceback (most recent call last):
  File "examples/basic.py", line 44, in <module>
    result = ctx.run(job)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\api.py", line 362, in run
    for tiles in self.executor.run_job(job_to_run):
  File "c:\users\weber\documents\libertem\libertem\src\libertem\executor\dask.py", line 97, in run_job
    for future, result in dd.as_completed(futures, with_results=True):
  File "C:\Program Files\Python36\lib\site-packages\distributed\client.py", line 3811, in __next__
    return self._get_and_raise()
  File "C:\Program Files\Python36\lib\site-packages\distributed\client.py", line 3802, in _get_and_raise
    six.reraise(*result)
  File "C:\Program Files\Python36\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\users\weber\documents\libertem\libertem\src\libertem\job\masks.py", line 189, in __call__
    torch.from_numpy(masks),
RuntimeError: size mismatch, m1: [8 x 16384], m2: [16256 x 1] at c:\a\w\1\s\windows\pytorch\aten\src\th\generic/THTensorMath.cpp:940
distributed.process - WARNING - reaping stray process <Process(Process-1, started daemon)>
distributed.process - WARNING - reaping stray process <Process(Process-2, started daemon)>
```

**Comment by uellue** [comment]
Is this good enough or do we need improvements? I'm closing because the new Shape class makes it easy to generate the right mask layout and this problem didn't happen to me for quite some time. Reopen if this is still an issue.
