### ISSUE TITLE
Proper error message or warning, and documentation for pywin32 install on Win

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#949]
When installing pywin32 on Windows for the first time, a post-install script has to be run with administrator privileges. Otherwise it will fail to load.

Since the error is a bit cryptic and hard to understand, we should handle it better and inform users.

- [x] Make pywin32 et al. optional, if possible, and warn instead of fail
- [x] Catch the error and provide a more helpful error message with info on how to fix it
- [ ] Include setting up pywin32 in install documentation

**Comment by uellue** [comment]
Importing `win32security` repeatedly if it is not set up properly can fail in an unexpected way. It seems to be a threading issue, perhaps a race condition. I'll look for a way to make sure importing is tried only once.

```
In [1]: import win32security
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-aa4a5800a20f> in <module>
----> 1 import win32security

ImportError: DLL load failed while importing win32security: The specified module could not be found.

In [2]: import win32security
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-aa4a5800a20f> in <module>
----> 1 import win32security

ImportError: DLL load failed while importing win32security: The specified module could not be found.

In [3]: import win32security
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-aa4a5800a20f> in <module>
----> 1 import win32security

ImportError: DLL load failed while importing win32security: The specified module could not be found.


Unhandled exception in event loop:
  File "c:\users\dieter\.conda\envs\libertem\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\dieter\.conda\envs\libertem\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\dieter\.conda\envs\libertem\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...
In [4]:
```

**Comment by uellue** [comment]
The `WinError 995` is also triggered if pywin32 is not installed in an environment and no import is attempted. It might have a different cause.

**Comment by uellue** [comment]
I can trigger it with very simple Python in a minimal environment with an `ipython` shell. I'll ignore it for now in the context of this Issue since it looks like an issue in `ipython` or one of its upstream packages.
